### ISSUE TITLE
game crashes on keybind setup

### ISSUE THREAD

**Issue by waeteet** [SamsDRGMods/SimpleQOL#42] opened 2023-03-17 16:49 UTC
game crashes upon setting a keybind to trigger a perk. after the crash, no keybind is set.

to reproduce, try setting a keybind to a shortcut for a perk

the game crashes with the crash screen showing the note that you have mods installed and they might be causing the crash

**Comment by SmoothMemes22** [comment] 2023-03-18 02:56
Same problem! Happens with any rebind.

**Comment by AydenWilson** [comment] 2023-03-26 11:39
Same for me.

**Comment by samamstar** [comment] 2023-04-03 23:34
Duplicate of #41

**Closed as completed by samamstar** 2023-04-03 23:34 UTC
Labels: bug
