### ISSUE TITLE
Crashes game on changing a keybind in the tweaks tab

### ISSUE THREAD

**Issue by Tyranicas** [SamsDRGMods/SimpleQOL#43] opened 2023-03-31 22:36 UTC
**Describe the bug**
When trying to change a keybind in the tweaks tab of SimpleQOL using modhub, the game crashes

**To Reproduce**
open mod hub, try to bind a key using the interface

**Expected behavior**

Keybind gets changed

**Screenshots**

**Additional context**

**Comment by samamstar** [comment] 2023-04-03 23:34
Duplicate of #42

**Comment by samamstar** [comment] 2023-04-03 23:35
Whoops I meant # 41

**Closed as completed by samamstar** 2023-04-03 23:34 UTC
Labels: bug
