### ISSUE TITLE
"IsSeasonMission" sorting and display broke after refresh a Challenge 

### ISSUE THREAD

**Issue by GoldMath** [SamsDRGMods/SimpleQOL#21] opened 2022-08-10 18:51 UTC
Hello, the feature working well but after refreshing a Challenge, the mod wasn't able again to display it. 
- Reloading the Space Rig or Restart the game didn't solve.
- Instead, it was solved at the next mission rotation. 

Regards,

- Extra QoL suggest about it: display a number on the "IsSeasonMission" logo if it's fulfill more than 1 challenges.
- Make sure to update your mod.io description mod with the new features.

----
_broken display_

![image](https://user-images.githubusercontent.com/7282547/183972494-6149e256-9857-44af-8ae4-136791227985.png)

**Comment by samamstar** [comment] 2022-08-25 14:43
I'm having difficulties reproducing this bug. While my list isn't refreshing after re-rolling challenges, it's cleared by opening and closing the SimpleQOL page, or adjusting the sorting so that the list re-sorts (Which I'll get fixed since that's kinda annoying). But it sounds like the bug you encountered is more involved. Do you have more detailed reproduction steps?

**Comment by samamstar** [comment] 2022-09-13 18:49
Cannot reproduce

**Closed by samamstar** 2022-09-13 18:49 UTC
Labels: bug
