### ISSUE TITLE
Crash to desktop when attempting to set a Custom Dash Binding

### ISSUE THREAD

**Issue by theoreminegaming** [SamsDRGMods/SimpleQOL#44] opened 2023-04-03 14:42 UTC
**Describe the bug**
Attempting to use the Dash perk rebind function at all results in a crash

**To Reproduce**
Open the mod manager menu to access settings, click on the custom dash binding button, press any key

**Expected behavior**
binding will update to the selected key

**Screenshots**

**Additional context**

**Comment by samamstar** [comment] 2023-04-03 23:34
Duplicate of #42

**Comment by samamstar** [comment] 2023-04-03 23:34
Whoops I meant #41

**Closed as completed by samamstar** 2023-04-03 23:34 UTC
Labels: bug
