### ISSUE TITLE
Ammo Resupply Indicator

### ISSUE THREAD

**Issue by Goofy-6** [SamsDRGMods/SimpleQOL#45] opened 2023-05-01 12:14 UTC
Hello, I'd like to request adding an updated ARI to SimpleQOL since the creator of it has no interest in maintaining the mod. I know there is the Ammo Percentage Indicator mod, but I much more prefer the way ARI handles things. It's much cleaner with only a simple color warning, instead of an entire HUD element taking up space. You could even take it a step further and add more colors for let's say, 75%, 50% 25%, and 0% of ammunition, but that is something I'd consider as a bonus feature and not something really needed.

**Comment by samamstar** [comment] 2023-05-02 01:54
Duplicate of #28. Don't hold your breath, I haven't made significant time for modding in a while

**Closed as completed** 2023-05-02 01:54 UTC
Labels: enhancement
